/**
 * ID Utility Functions
 *
 * Provides utilities for generating temporary IDs for optimistic updates
 * and other ID-related operations.
 */

/**
 * Generates a temporary ID for optimistic updates.
 * Format: temp-<timestamp>-<random>
 * Used for Build, Part, TestRun entities before server confirmation.
 *
 * @returns A temporary ID string
 *
 * @example
 * const tempId = generateTempId();
 * // => "temp-1703001234567-a7f2c"
 */
export function generateTempId(): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 7);
  return `temp-${timestamp}-${random}`;
}

/**
 * Checks if an ID is a temporary ID (generated by optimistic updates).
 *
 * @param id - The ID to check
 * @returns True if the ID is a temporary ID
 *
 * @example
 * isTempId('temp-1703001234567-a7f2c'); // => true
 * isTempId('123'); // => false
 */
export function isTempId(id: string): boolean {
  return id.startsWith('temp-');
}
